### PR TITLE
Added Yii2 Api client

### PR DESCRIPTION
**Pull request by lordthorzonus**
Hi! Added my package to the list. I'm not sure if it's under the right heading. Technically it's an API client but all the clients under that heading were official ones. 

Thanks for an awesome product 👍.

### CODE REVIEW

**Comment by lordthorzonus** [comment]
@Haroenv You were faster than me resolving conflicts :).

**Comment by rayrutjes** [comment]
Thanks @lordthorzonus !

We should as much as possible, always add new entries at the end of the lists.

If at some point, it doesn't make sense because libs with same purposes are scattered around, then we need to introduce new sections.

**Comment by lordthorzonus** [comment]
@rayrutjes Conflict resolved wrong :). Rebased and corrected the order of entries.

**Comment by Haroenv** [comment]
My fault 😂

**Comment by rayrutjes** [comment]
All good ;) thanks @lordthorzonus  and let us know if you need anything!

Also please feel free to [present your project](https://discourse.algolia.com/c/projects) on our forum & or ask questions there: 

https://discourse.algolia.com/

Cheers!

**Pull request merged**
