### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by belazer**
Add GraphCMS in Community Integrations

### CODE REVIEW

**Comment by rayrutjes** [comment]
Thanks for the contribution!
Could you add it to the end of the community list?

**Comment by Haroenv** [comment]
Hey @belazer, thanks for adding this; it looks really good. A tiny remark: you're using our old logo in the left top corner of the dashboard and also in the documentation screenshots of it, it would be nice to fix that 😄

**Comment by belazer** [comment]
@Haroenv This is just the image for the example project I used for this case. The image up there is whatever you set as your project image. Which other screenshots are you referring to?

**Comment by rayrutjes** [comment]
I think he refers to:
image

Thanks for adjusting the PR!

**Comment by belazer** [comment]
Yeah that's just the image I set for the project. A user can upload whatever image they like, but I will update it with your new logo tomorrow! 🙌

**Comment by rayrutjes** [comment]
Thanks @belazer !

**Pull request merged**
