### PR TITLE
Add windtoday.co

### PR DESCRIPTION
**Pull request by Kikobeats**

### CODE REVIEW

**Comment by rayrutjes** [comment]
Hi @Kikobeats ,

Thanks a lot for pushing this! ❤️ 

Would you mind passing the `autocomplete` attribute to `off` for the main search input?

image

**Comment by Kikobeats** [comment]
Thanks for the feedback!

Currrently `autocomplete` is not enabled, or need to be disabled explicity?

I think that you are showing [previous results](https://github.com/windtoday/windtoday-app/blob/a85c833ffae5c723661389bc57bed374f862120c/src/app/SearchBox/index.js#L60)

**Comment by rayrutjes** [comment]
Looks like we found a bug ;) about to fix that in instantsearch react 👍 

Autocomplete attribute of the search box should be set to "off" by default, not "false".

https://github.com/algolia/instantsearch.js/issues/1741

@dzello can you review the website of @Kikobeats ?

**Comment by dzello** [comment]
Looks awesome, gg @Kikobeats! 💨

**Comment by dzello** [comment]
@Kikobeats toss up a link on https://discourse.algolia.com/c/built-with-algolia, we're going to release the forum more broadly this week and that'll get your project some 👁

**Pull request merged**
