### PR TITLE
Reference the "Other" category into the summary

### PR DESCRIPTION
**Pull request by LukyVj**
✨

### CODE REVIEW

**Comment by dzello** [comment]
Nice! But maybe you need this url: [https://github.com/algolia/awesome-algolia#other](https://github.com/algolia/awesome-algolia#other)

**Comment by LukyVj** [comment]
Oh ? I added that id because of this :

**Comment by dzello** [comment]
Ah I see, that could work but `user-content` is something based on what Github adds. Maybe better to base it on the `href` attribute that is fully under our control?

**Comment by LukyVj** [comment]
Should be good now @dzello

**Comment by dzello** [comment]
Awesome, thanks!

**Pull request merged**
